apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: democap
  labels:
    app: redis
data:
  dir: "/var/lib/redis"
  port: "6379"
  bind: 0.0.0.0
  appendonly: "yes"
  protected-mode: "no"
